server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: classpath:env.yml

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
